spring:
  application:
    name: restapiwithvalidation
  datasource:
    username: postgres
    password: 
    url: jdbc:postgresql://localhost:5432/studcrudproject
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
